pipeline:
  build:
    image: node:6.9.1
    cmd: 
      - npm npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build
  docker:
    image: plugins/docker
    # username: kevinbacon
    # password: pa55word
    # email: kevin.bacon@mail.com
    # repo: foo/bar
    # tags: latest
  publish:
    image: scp